#!/usr/bin/env bash
set -euo pipefail

# scripts/azure-deploy.fixed.sh
#
# Deploy behavior:
# - no resource group deletion
# - local Docker build by default (Azure for Students friendly)
# - safe temporary Docker config by default
# - fixed demo credentials by default (unless explicitly overridden by caller)
# - optional migration/seed job execution after deploy
# - always persists resolved config to .azure-deploy.env (also on failures)

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"
ENV_FILE="$ROOT_DIR/.azure-deploy.env"

DEPLOY_STATE="starting"
DEPLOY_LAST_STEP="bootstrap"
DEPLOY_LAST_ERROR=""
DEPLOY_UPDATED_AT_UTC=""

write_env_var() {
  local name="$1"
  local value="${!name-}"
  printf '%s=%q\n' "$name" "$value"
}

persist_env_file() {
  DEPLOY_UPDATED_AT_UTC="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  {
    echo "# Generated by scripts/azure-deploy.fixed.sh. Contains secrets; do not commit."
    write_env_var RESOURCE_GROUP
    write_env_var LOCATION
    write_env_var PREFIX
    write_env_var ACR_NAME
    write_env_var START_ENABLED
    write_env_var APP_SECRET_KEY
    write_env_var POSTGRES_PASSWORD
    write_env_var OPENCODE_API_KEY
    write_env_var SEED_DEMO_USERS
    write_env_var DEMO_ADMIN_PASSWORD
    write_env_var DEMO_CURATOR_PASSWORD
    write_env_var DEMO_ANALYST_PASSWORD
    write_env_var DEMO_USER_PASSWORD
    write_env_var ACR_BUILD_MODE
    write_env_var RESOLVED_ACR_BUILD_MODE
    write_env_var DEMO_PASSWORD_MODE
    write_env_var RUN_MIGRATIONS
    write_env_var USE_TEMP_DOCKER_CONFIG
    write_env_var DEPLOY_STATE
    write_env_var DEPLOY_LAST_STEP
    write_env_var DEPLOY_LAST_ERROR
    write_env_var DEPLOY_UPDATED_AT_UTC
  } > "$ENV_FILE"
  chmod 600 "$ENV_FILE"
}

set_step() {
  DEPLOY_LAST_STEP="$1"
  DEPLOY_STATE="running"
  persist_env_file
}

on_exit() {
  local exit_code=$?

  if [[ "$exit_code" -eq 0 ]]; then
    DEPLOY_STATE="succeeded"
    DEPLOY_LAST_ERROR=""
  else
    DEPLOY_STATE="failed"
    DEPLOY_LAST_ERROR="step=${DEPLOY_LAST_STEP} exit_code=${exit_code}"
  fi

  persist_env_file || true

  if [[ "$exit_code" -ne 0 ]]; then
    echo >&2
    echo "Deploy failed at step: ${DEPLOY_LAST_STEP} (exit ${exit_code})." >&2
    echo "Resolved values were written to: ${ENV_FILE}" >&2
    echo "Tip: if app login still fails after retry, run ./scripts/force-reset-demo-hashes-v2.sh" >&2
  fi
}
trap on_exit EXIT

need_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "Missing required command: $1" >&2
    exit 1
  fi
}

is_hash_like() {
  local value="$1"
  [[ "$value" =~ ^\$pbkdf2-sha256\$ ]] || [[ "$value" =~ ^\$2[aby]\$ ]] || [[ "$value" =~ ^\$argon2 ]]
}

warn_if_hash_like_password() {
  local name="$1"
  local value="${!name-}"
  if [[ -n "$value" ]] && is_hash_like "$value"; then
    echo "WARNING: $name looks like a password hash. Provide plaintext password, not hash." >&2
  fi
}

need_cmd az
need_cmd openssl

# Reuse values from previous deployment so redeploy does not rotate secrets behind
# already-mounted volumes. Explicit caller env vars still win.
_EXTERNAL_RESOURCE_GROUP="${RESOURCE_GROUP-}"
_EXTERNAL_LOCATION="${LOCATION-}"
_EXTERNAL_PREFIX="${PREFIX-}"
_EXTERNAL_ACR_NAME="${ACR_NAME-}"
_EXTERNAL_START_ENABLED="${START_ENABLED-}"
_EXTERNAL_APP_SECRET_KEY="${APP_SECRET_KEY-}"
_EXTERNAL_POSTGRES_PASSWORD="${POSTGRES_PASSWORD-}"
_EXTERNAL_OPENCODE_API_KEY="${OPENCODE_API_KEY-}"
_EXTERNAL_SEED_DEMO_USERS="${SEED_DEMO_USERS-}"
_EXTERNAL_DEMO_ADMIN_PASSWORD="${DEMO_ADMIN_PASSWORD-}"
_EXTERNAL_DEMO_CURATOR_PASSWORD="${DEMO_CURATOR_PASSWORD-}"
_EXTERNAL_DEMO_ANALYST_PASSWORD="${DEMO_ANALYST_PASSWORD-}"
_EXTERNAL_DEMO_USER_PASSWORD="${DEMO_USER_PASSWORD-}"
_EXTERNAL_ACR_BUILD_MODE="${ACR_BUILD_MODE-}"
_EXTERNAL_DEMO_PASSWORD_MODE="${DEMO_PASSWORD_MODE-}"
_EXTERNAL_RUN_MIGRATIONS="${RUN_MIGRATIONS-}"
_EXTERNAL_USE_TEMP_DOCKER_CONFIG="${USE_TEMP_DOCKER_CONFIG-}"

if [[ -f "$ENV_FILE" ]]; then
  # shellcheck disable=SC1090
  source "$ENV_FILE"
fi

[[ -n "$_EXTERNAL_RESOURCE_GROUP" ]] && RESOURCE_GROUP="$_EXTERNAL_RESOURCE_GROUP"
[[ -n "$_EXTERNAL_LOCATION" ]] && LOCATION="$_EXTERNAL_LOCATION"
[[ -n "$_EXTERNAL_PREFIX" ]] && PREFIX="$_EXTERNAL_PREFIX"
[[ -n "$_EXTERNAL_ACR_NAME" ]] && ACR_NAME="$_EXTERNAL_ACR_NAME"
[[ -n "$_EXTERNAL_START_ENABLED" ]] && START_ENABLED="$_EXTERNAL_START_ENABLED"
[[ -n "$_EXTERNAL_APP_SECRET_KEY" ]] && APP_SECRET_KEY="$_EXTERNAL_APP_SECRET_KEY"
[[ -n "$_EXTERNAL_POSTGRES_PASSWORD" ]] && POSTGRES_PASSWORD="$_EXTERNAL_POSTGRES_PASSWORD"
[[ -n "$_EXTERNAL_OPENCODE_API_KEY" ]] && OPENCODE_API_KEY="$_EXTERNAL_OPENCODE_API_KEY"
[[ -n "$_EXTERNAL_SEED_DEMO_USERS" ]] && SEED_DEMO_USERS="$_EXTERNAL_SEED_DEMO_USERS"
[[ -n "$_EXTERNAL_DEMO_ADMIN_PASSWORD" ]] && DEMO_ADMIN_PASSWORD="$_EXTERNAL_DEMO_ADMIN_PASSWORD"
[[ -n "$_EXTERNAL_DEMO_CURATOR_PASSWORD" ]] && DEMO_CURATOR_PASSWORD="$_EXTERNAL_DEMO_CURATOR_PASSWORD"
[[ -n "$_EXTERNAL_DEMO_ANALYST_PASSWORD" ]] && DEMO_ANALYST_PASSWORD="$_EXTERNAL_DEMO_ANALYST_PASSWORD"
[[ -n "$_EXTERNAL_DEMO_USER_PASSWORD" ]] && DEMO_USER_PASSWORD="$_EXTERNAL_DEMO_USER_PASSWORD"
[[ -n "$_EXTERNAL_ACR_BUILD_MODE" ]] && ACR_BUILD_MODE="$_EXTERNAL_ACR_BUILD_MODE"
[[ -n "$_EXTERNAL_DEMO_PASSWORD_MODE" ]] && DEMO_PASSWORD_MODE="$_EXTERNAL_DEMO_PASSWORD_MODE"
[[ -n "$_EXTERNAL_RUN_MIGRATIONS" ]] && RUN_MIGRATIONS="$_EXTERNAL_RUN_MIGRATIONS"
[[ -n "$_EXTERNAL_USE_TEMP_DOCKER_CONFIG" ]] && USE_TEMP_DOCKER_CONFIG="$_EXTERNAL_USE_TEMP_DOCKER_CONFIG"

RESOURCE_GROUP="${RESOURCE_GROUP:-rg-xdub-2220}"
LOCATION="${LOCATION:-westus2}"
PREFIX="${PREFIX:-xdubrag}"

# Defaults tuned for easier dev deployments
START_ENABLED="${START_ENABLED:-true}"
ACR_BUILD_MODE="${ACR_BUILD_MODE:-local}"
DEMO_PASSWORD_MODE="${DEMO_PASSWORD_MODE:-fixed}"
RUN_MIGRATIONS="${RUN_MIGRATIONS:-true}"
USE_TEMP_DOCKER_CONFIG="${USE_TEMP_DOCKER_CONFIG:-true}"

if [[ ! "$PREFIX" =~ ^[a-z0-9][a-z0-9-]{1,18}[a-z0-9]$ ]]; then
  echo "PREFIX must be lowercase letters/numbers/hyphen, 3-20 chars, no leading/trailing hyphen." >&2
  exit 1
fi

if [[ "$START_ENABLED" != "true" && "$START_ENABLED" != "false" ]]; then
  echo "START_ENABLED must be true or false." >&2
  exit 1
fi

if [[ "$ACR_BUILD_MODE" != "auto" && "$ACR_BUILD_MODE" != "remote" && "$ACR_BUILD_MODE" != "local" ]]; then
  echo "ACR_BUILD_MODE must be auto, remote, or local." >&2
  exit 1
fi

if [[ "$DEMO_PASSWORD_MODE" != "fixed" && "$DEMO_PASSWORD_MODE" != "random" && "$DEMO_PASSWORD_MODE" != "preserve" ]]; then
  echo "DEMO_PASSWORD_MODE must be fixed, random, or preserve." >&2
  exit 1
fi

if [[ "$RUN_MIGRATIONS" != "true" && "$RUN_MIGRATIONS" != "false" ]]; then
  echo "RUN_MIGRATIONS must be true or false." >&2
  exit 1
fi

if [[ "$USE_TEMP_DOCKER_CONFIG" != "true" && "$USE_TEMP_DOCKER_CONFIG" != "false" ]]; then
  echo "USE_TEMP_DOCKER_CONFIG must be true or false." >&2
  exit 1
fi

APP_SECRET_KEY="${APP_SECRET_KEY:-$(openssl rand -hex 32)}"
POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-$(openssl rand -hex 20)}"
OPENCODE_API_KEY="${OPENCODE_API_KEY:-}"
SEED_DEMO_USERS="${SEED_DEMO_USERS:-true}"

if [[ "$SEED_DEMO_USERS" != "true" && "$SEED_DEMO_USERS" != "false" ]]; then
  echo "SEED_DEMO_USERS must be true or false." >&2
  exit 1
fi

# Demo password behavior:
# fixed    = force known defaults unless caller explicitly exported DEMO_* before running
# random   = old behavior; generate random hex if not already set
# preserve = keep values from .azure-deploy.env if present, otherwise fixed defaults
case "$DEMO_PASSWORD_MODE" in
  fixed)
    if [[ -z "$_EXTERNAL_DEMO_ADMIN_PASSWORD" ]]; then DEMO_ADMIN_PASSWORD="admin123"; fi
    if [[ -z "$_EXTERNAL_DEMO_CURATOR_PASSWORD" ]]; then DEMO_CURATOR_PASSWORD="curator123"; fi
    if [[ -z "$_EXTERNAL_DEMO_ANALYST_PASSWORD" ]]; then DEMO_ANALYST_PASSWORD="analyst123"; fi
    if [[ -z "$_EXTERNAL_DEMO_USER_PASSWORD" ]]; then DEMO_USER_PASSWORD="user123"; fi

    [[ -n "$_EXTERNAL_DEMO_ADMIN_PASSWORD" ]] && echo "Notice: DEMO_ADMIN_PASSWORD was explicitly provided by caller; using it." >&2
    [[ -n "$_EXTERNAL_DEMO_CURATOR_PASSWORD" ]] && echo "Notice: DEMO_CURATOR_PASSWORD was explicitly provided by caller; using it." >&2
    [[ -n "$_EXTERNAL_DEMO_ANALYST_PASSWORD" ]] && echo "Notice: DEMO_ANALYST_PASSWORD was explicitly provided by caller; using it." >&2
    [[ -n "$_EXTERNAL_DEMO_USER_PASSWORD" ]] && echo "Notice: DEMO_USER_PASSWORD was explicitly provided by caller; using it." >&2
    ;;
  random)
    DEMO_ADMIN_PASSWORD="${DEMO_ADMIN_PASSWORD:-$(openssl rand -hex 8)}"
    DEMO_CURATOR_PASSWORD="${DEMO_CURATOR_PASSWORD:-$(openssl rand -hex 8)}"
    DEMO_ANALYST_PASSWORD="${DEMO_ANALYST_PASSWORD:-$(openssl rand -hex 8)}"
    DEMO_USER_PASSWORD="${DEMO_USER_PASSWORD:-$(openssl rand -hex 8)}"
    ;;
  preserve)
    DEMO_ADMIN_PASSWORD="${DEMO_ADMIN_PASSWORD:-admin123}"
    DEMO_CURATOR_PASSWORD="${DEMO_CURATOR_PASSWORD:-curator123}"
    DEMO_ANALYST_PASSWORD="${DEMO_ANALYST_PASSWORD:-analyst123}"
    DEMO_USER_PASSWORD="${DEMO_USER_PASSWORD:-user123}"
    ;;
esac

warn_if_hash_like_password DEMO_ADMIN_PASSWORD
warn_if_hash_like_password DEMO_CURATOR_PASSWORD
warn_if_hash_like_password DEMO_ANALYST_PASSWORD
warn_if_hash_like_password DEMO_USER_PASSWORD

if [[ "$USE_TEMP_DOCKER_CONFIG" == "true" && -z "${DOCKER_CONFIG-}" ]]; then
  export DOCKER_CONFIG="$ROOT_DIR/.docker-acr-temp"
  mkdir -p "$DOCKER_CONFIG"
fi

set_step "resolved-config"

echo "Deploy settings:"
echo "  RESOURCE_GROUP=$RESOURCE_GROUP"
echo "  LOCATION=$LOCATION"
echo "  PREFIX=$PREFIX"
echo "  START_ENABLED=$START_ENABLED"
echo "  ACR_BUILD_MODE=$ACR_BUILD_MODE"
echo "  DEMO_PASSWORD_MODE=$DEMO_PASSWORD_MODE"
echo "  SEED_DEMO_USERS=$SEED_DEMO_USERS"
echo "  RUN_MIGRATIONS=$RUN_MIGRATIONS"
if [[ -n "${DOCKER_CONFIG-}" ]]; then
  echo "  DOCKER_CONFIG=$DOCKER_CONFIG"
fi
echo
echo "Demo credentials that will be passed to deployment:"
echo "  admin   / $DEMO_ADMIN_PASSWORD"
echo "  curator / $DEMO_CURATOR_PASSWORD"
echo "  analyst / $DEMO_ANALYST_PASSWORD"
echo "  user    / $DEMO_USER_PASSWORD"
echo

set_step "azure-account"
az account show >/dev/null
SUB_ID_COMPACT="$(az account show --query id -o tsv | tr -d '-' | cut -c1-8)"
ACR_NAME="${ACR_NAME:-$(echo "${PREFIX}acr${SUB_ID_COMPACT}" | tr -d '-' | tr '[:upper:]' '[:lower:]' | cut -c1-50)}"

set_step "azure-register-providers"
az extension add -n containerapp --upgrade >/dev/null
az provider register --namespace Microsoft.App --wait >/dev/null
az provider register --namespace Microsoft.OperationalInsights --wait >/dev/null
az provider register --namespace Microsoft.ContainerRegistry --wait >/dev/null
az provider register --namespace Microsoft.Storage --wait >/dev/null

set_step "azure-resource-group"
az group create --name "$RESOURCE_GROUP" --location "$LOCATION" >/dev/null

set_step "azure-acr"
if ! az acr show --name "$ACR_NAME" --resource-group "$RESOURCE_GROUP" >/dev/null 2>&1; then
  az acr create \
    --resource-group "$RESOURCE_GROUP" \
    --name "$ACR_NAME" \
    --sku Basic \
    --admin-enabled true >/dev/null
else
  az acr update --name "$ACR_NAME" --admin-enabled true >/dev/null
fi

ACR_LOGIN_SERVER="$(az acr show -n "$ACR_NAME" -g "$RESOURCE_GROUP" --query loginServer -o tsv)"
ACR_USERNAME="$(az acr credential show -n "$ACR_NAME" --query username -o tsv)"
ACR_PASSWORD="$(az acr credential show -n "$ACR_NAME" --query passwords[0].value -o tsv)"

API_IMAGE="${ACR_LOGIN_SERVER}/${PREFIX}-api:latest"
MIGRATE_IMAGE="${ACR_LOGIN_SERVER}/${PREFIX}-migrate:latest"
FRONTEND_IMAGE="${ACR_LOGIN_SERVER}/${PREFIX}-frontend:latest"

RESOLVED_ACR_BUILD_MODE="$ACR_BUILD_MODE"
local_build_ready="false"

ensure_local_build_ready() {
  if [[ "$local_build_ready" == "true" ]]; then
    return 0
  fi

  if ! command -v docker >/dev/null 2>&1; then
    echo "Docker CLI is required for local image builds. Install Docker or set ACR_BUILD_MODE=remote." >&2
    exit 1
  fi

  if ! docker info >/dev/null 2>&1; then
    echo "Docker daemon is not running. Start Docker or set ACR_BUILD_MODE=remote." >&2
    exit 1
  fi

  printf '%s' "$ACR_PASSWORD" | docker login "$ACR_LOGIN_SERVER" --username "$ACR_USERNAME" --password-stdin >/dev/null
  local_build_ready="true"
}

build_image_local() {
  local full_image="$1"
  local dockerfile="$2"
  local context="$3"
  ensure_local_build_ready
  docker build -t "$full_image" -f "$dockerfile" "$context"
  docker push "$full_image"
}

build_image() {
  local short_tag="$1"
  local full_image="$2"
  local dockerfile="$3"
  local context="$4"

  if [[ "$RESOLVED_ACR_BUILD_MODE" == "local" ]]; then
    build_image_local "$full_image" "$dockerfile" "$context"
    return 0
  fi

  if [[ "$RESOLVED_ACR_BUILD_MODE" == "remote" ]]; then
    az acr build -r "$ACR_NAME" -t "$short_tag" -f "$dockerfile" "$context"
    return 0
  fi

  local build_output
  if build_output="$(az acr build -r "$ACR_NAME" -t "$short_tag" -f "$dockerfile" "$context" 2>&1)"; then
    printf '%s\n' "$build_output"
    return 0
  fi

  printf '%s\n' "$build_output" >&2
  if grep -q "TasksOperationsNotAllowed" <<<"$build_output"; then
    echo "ACR Tasks are not allowed in this subscription. Falling back to local Docker build/push." >&2
    RESOLVED_ACR_BUILD_MODE="local"
    persist_env_file
    build_image_local "$full_image" "$dockerfile" "$context"
    return 0
  fi

  return 1
}

wait_job_execution() {
  local job_name="$1"
  local execution_name="$2"
  local timeout="${3:-900}"
  local elapsed=0

  while true; do
    local status
    status="$(az containerapp job execution show \
      -g "$RESOURCE_GROUP" \
      -n "$job_name" \
      --job-execution-name "$execution_name" \
      --query properties.status \
      -o tsv 2>/dev/null || echo Unknown)"

    echo "  $job_name status=$status elapsed=${elapsed}s"

    case "$status" in
      Succeeded)
        return 0
        ;;
      Failed|Error)
        echo "Job failed: $job_name / $execution_name" >&2
        echo "Logs:" >&2
        az containerapp job logs show \
          -g "$RESOURCE_GROUP" \
          -n "$job_name" \
          --job-execution-name "$execution_name" \
          --tail 300 2>/dev/null || true
        return 1
        ;;
    esac

    if [[ "$elapsed" -ge "$timeout" ]]; then
      echo "Timeout waiting for job: $job_name / $execution_name" >&2
      echo "Check logs with:" >&2
      echo "  az containerapp job logs show -g \"$RESOURCE_GROUP\" -n \"$job_name\" --job-execution-name \"$execution_name\" --tail 300" >&2
      return 1
    fi

    sleep 10
    elapsed=$((elapsed + 10))
  done
}

set_step "build-api-image"
build_image "${PREFIX}-api:latest" "$API_IMAGE" "Dockerfile" "."

set_step "build-migrate-image"
build_image "${PREFIX}-migrate:latest" "$MIGRATE_IMAGE" "Dockerfile.migrate" "."

set_step "build-frontend-image"
build_image "${PREFIX}-frontend:latest" "$FRONTEND_IMAGE" "frontend/Dockerfile" "./frontend"

set_step "deploy-bicep"
az deployment group create \
  --resource-group "$RESOURCE_GROUP" \
  --template-file infra/main.bicep \
  --parameters \
    location="$LOCATION" \
    prefix="$PREFIX" \
    acrLoginServer="$ACR_LOGIN_SERVER" \
    acrUsername="$ACR_USERNAME" \
    acrPassword="$ACR_PASSWORD" \
    apiImage="$API_IMAGE" \
    frontendImage="$FRONTEND_IMAGE" \
    migrateImage="$MIGRATE_IMAGE" \
    appSecretKey="$APP_SECRET_KEY" \
    postgresPassword="$POSTGRES_PASSWORD" \
    opencodeApiKey="$OPENCODE_API_KEY" \
    seedDemoUsers="$SEED_DEMO_USERS" \
    demoAdminPassword="$DEMO_ADMIN_PASSWORD" \
    demoCuratorPassword="$DEMO_CURATOR_PASSWORD" \
    demoAnalystPassword="$DEMO_ANALYST_PASSWORD" \
    demoUserPassword="$DEMO_USER_PASSWORD" \
    startEnabled="$START_ENABLED"

if [[ "$RUN_MIGRATIONS" == "true" ]]; then
  JOB_NAME="${PREFIX}-migrate"

  if az containerapp job show -g "$RESOURCE_GROUP" -n "$JOB_NAME" >/dev/null 2>&1; then
    set_step "run-migrations"
    echo
    echo "Starting migration/seed job: $JOB_NAME"
    az containerapp job start -g "$RESOURCE_GROUP" -n "$JOB_NAME" >/dev/null

    sleep 8
    EXECUTION_NAME="$(az containerapp job execution list \
      -g "$RESOURCE_GROUP" \
      -n "$JOB_NAME" \
      --query "sort_by(@,&properties.startTime)[-1].name" \
      -o tsv)"

    if [[ -z "$EXECUTION_NAME" ]]; then
      echo "Could not determine latest execution for $JOB_NAME" >&2
      exit 1
    fi

    wait_job_execution "$JOB_NAME" "$EXECUTION_NAME" 900
  else
    echo "Migration job not found: $JOB_NAME. Skipping RUN_MIGRATIONS." >&2
  fi
fi

set_step "final-output"

echo
echo "Deployment created/updated. Config saved to .azure-deploy.env"
echo
echo "Container Apps:"
az containerapp list -g "$RESOURCE_GROUP" --query "[].{name:name,fqdn:properties.configuration.ingress.fqdn,provisioning:properties.provisioningState}" -o table || true
echo
echo "Demo credentials:"
echo "  admin   / $DEMO_ADMIN_PASSWORD"
echo "  curator / $DEMO_CURATOR_PASSWORD"
echo "  analyst / $DEMO_ANALYST_PASSWORD"
echo "  user    / $DEMO_USER_PASSWORD"
echo
echo "Start: ./scripts/azure-start.sh"
echo "Stop:  ./scripts/azure-stop.sh"
